version: '3.3'

services:
  dockerRun: 
    network_mode: bridge
    restart: always
    container_name: spring_docker
    image: testimg:assgn
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"   
    ports:
      - "8096:8080"
